'use client'

import { useState } from 'react'

type Status = 'idle' | 'processing' | 'complete' | 'error'

type Report = {
  mode: 'ai' | 'demo' | 'worker'
  summary: string
  scoreline: string
  keyInsights: string[]
  trainingFocus: string[]
  timeline: { minute: string; note: string }[]
  nextSteps: string[]
  rawAnalysis?: string
}

function isVideoUrl(value: string) {
  return value.includes('youtube.com') || value.includes('youtu.be') || value.includes('vimeo.com') || value.includes('veo.co')
}

function escapeHtml(value: string) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;')
}

function renderList(items: string[]) {
  return items.map((item) => `<li>${escapeHtml(item)}</li>`).join('')
}

function downloadReport(report: Report, matchTitle: string) {
  const fullReport = report.rawAnalysis || [
    `GAELIC COACH AI - MATCH REPORT`,
    ``,
    `EXECUTIVE SUMMARY`,
    report.summary,
    ``,
    `SCORELINE`,
    report.scoreline,
    ``,
    `KEY TACTICAL THEMES`,
    ...report.keyInsights.map((item) => `- ${item}`),
    ``,
    `TRAINING PRIORITIES`,
    ...report.trainingFocus.map((item) => `- ${item}`),
    ``,
    `COACH ACTIONS`,
    ...report.nextSteps.map((item) => `- ${item}`)
  ].join('\n')

  const htmlReport = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${escapeHtml(matchTitle)} - Gaelic Coach AI Report</title>
  <style>
    body { margin: 0; background: #f4f7fb; color: #0f172a; font-family: Arial, sans-serif; }
    .page { max-width: 980px; margin: 40px auto; background: white; border-radius: 28px; overflow: hidden; box-shadow: 0 24px 80px rgba(15,23,42,.14); }
    .hero { background: linear-gradient(135deg,#0f172a,#065f46); color: white; padding: 42px; }
    .eyebrow { color: #a7f3d0; font-size: 12px; text-transform: uppercase; letter-spacing: .22em; font-weight: 700; }
    h1 { margin: 14px 0 0; font-size: 38px; line-height: 1.05; }
    .meta { margin-top: 16px; color: #d1fae5; font-size: 14px; }
    .content { padding: 38px 42px 46px; }
    .grid { display: grid; grid-template-columns: repeat(3,1fr); gap: 14px; margin-bottom: 28px; }
    .stat { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 18px; padding: 18px; }
    .label { font-size: 11px; color: #64748b; text-transform: uppercase; letter-spacing: .12em; font-weight: 700; }
    .value { margin-top: 8px; font-size: 15px; font-weight: 700; }
    section { margin-top: 30px; }
    h2 { font-size: 22px; margin: 0 0 12px; }
    p { color: #334155; line-height: 1.7; }
    ul { padding-left: 20px; color: #334155; line-height: 1.7; }
    li { margin-bottom: 8px; }
    .full { white-space: pre-wrap; background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 20px; padding: 22px; color: #334155; line-height: 1.7; }
    .footer { border-top: 1px solid #e2e8f0; padding-top: 18px; margin-top: 32px; color: #64748b; font-size: 12px; }
    @media print { body { background: white; } .page { margin: 0; box-shadow: none; border-radius: 0; } }
  </style>
</head>
<body>
  <div class="page">
    <div class="hero">
      <div class="eyebrow">Gaelic Coach AI</div>
      <h1>${escapeHtml(matchTitle)}</h1>
      <div class="meta">AI-assisted tactical report • ${escapeHtml(report.scoreline)}</div>
    </div>
    <div class="content">
      <div class="grid">
        <div class="stat"><div class="label">Scoreline</div><div class="value">${escapeHtml(report.scoreline)}</div></div>
        <div class="stat"><div class="label">Themes</div><div class="value">${report.keyInsights.length} insights</div></div>
        <div class="stat"><div class="label">Training</div><div class="value">${report.trainingFocus.length} priorities</div></div>
      </div>
      <section><h2>Executive Summary</h2><p>${escapeHtml(report.summary)}</p></section>
      <section><h2>Key Tactical Themes</h2><ul>${renderList(report.keyInsights)}</ul></section>
      <section><h2>Training Priorities</h2><ul>${renderList(report.trainingFocus)}</ul></section>
      <section><h2>Coach Actions</h2><ul>${renderList(report.nextSteps)}</ul></section>
      <section><h2>Full Analyst Notes</h2><div class="full">${escapeHtml(fullReport)}</div></section>
      <div class="footer">Generated by Gaelic Coach AI. This report should support, not replace, coach judgement and video review.</div>
    </div>
  </div>
</body>
</html>`

  const blob = new Blob([htmlReport], { type: 'text/html;charset=utf-8' })
  const href = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = href
  link.download = 'gaelic-coach-ai-premium-match-report.html'
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(href)
}

export default function YouTubeAnalyser() {
  const [url, setUrl] = useState('')
  const [teamA, setTeamA] = useState('')
  const [teamB, setTeamB] = useState('')
  const [coachedTeam, setCoachedTeam] = useState('')
  const [teamAColour, setTeamAColour] = useState('')
  const [teamBColour, setTeamBColour] = useState('')
  const [teamAGoals, setTeamAGoals] = useState('')
  const [teamAPoints, setTeamAPoints] = useState('')
  const [teamBGoals, setTeamBGoals] = useState('')
  const [teamBPoints, setTeamBPoints] = useState('')
  const [competition, setCompetition] = useState('')
  const [notes, setNotes] = useState('')
  const [status, setStatus] = useState<Status>('idle')
  const [error, setError] = useState('')
  const [report, setReport] = useState<Report | null>(null)

  const scoreComplete = teamAGoals !== '' && teamAPoints !== '' && teamBGoals !== '' && teamBPoints !== ''
  const requiredFieldsComplete = Boolean(url && teamA && teamB && coachedTeam && teamAColour && teamBColour && scoreComplete)
  const matchTitle = `${teamA || 'Team A'} vs ${teamB || 'Team B'}`

  async function analyse() {
    setError('')
    setReport(null)

    if (!isVideoUrl(url)) {
      setStatus('error')
      setError('Please enter a valid YouTube, Vimeo, or Veo link.')
      return
    }

    if (!requiredFieldsComplete) {
      setStatus('error')
      setError('Please complete the required match context: teams, coached team, colours and goals/points for both teams.')
      return
    }

    setStatus('processing')

    const matchContext = {
      teamA,
      teamB,
      coachedTeam,
      teamAColour,
      teamBColour,
      teamAGoals: Number(teamAGoals),
      teamAPoints: Number(teamAPoints),
      teamBGoals: Number(teamBGoals),
      teamBPoints: Number(teamBPoints),
      competition
    }

    try {
      const response = await fetch('/api/analyse-link', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url, notes, matchContext })
      })

      const data = await response.json()

      if (!response.ok) {
        setStatus('error')
        setError(data.error ?? 'Unable to analyse this link.')
        return
      }

      setReport(data)
      setStatus('complete')
    } catch {
      setStatus('error')
      setError('Unable to connect to the analysis service.')
    }
  }

  return (
    <div className="rounded-[2rem] border border-slate-200 bg-white p-6 shadow-2xl shadow-slate-200/70">
      <p className="text-xl font-bold text-slate-950">Analyse a match link</p>
      <p className="mt-2 text-sm text-slate-500">
        Add match context first. The full report is downloaded separately so the page stays clean.
      </p>

      <div className="mt-6 space-y-4">
        <input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="YouTube, Vimeo or Veo match link" className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-4 text-slate-950 outline-none placeholder:text-slate-400 focus:border-emerald-400 focus:ring-4 focus:ring-emerald-100" />

        <div className="grid gap-3 md:grid-cols-2">
          <input value={teamA} onChange={(event) => setTeamA(event.target.value)} placeholder="Team A name *" className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-slate-950 outline-none placeholder:text-slate-400 focus:border-emerald-400 focus:ring-4 focus:ring-emerald-100" />
          <input value={teamB} onChange={(event) => setTeamB(event.target.value)} placeholder="Team B name *" className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-slate-950 outline-none placeholder:text-slate-400 focus:border-emerald-400 focus:ring-4 focus:ring-emerald-100" />
          <input value={teamAColour} onChange={(event) => setTeamAColour(event.target.value)} placeholder="Team A colours *" className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-slate-950 outline-none placeholder:text-slate-400 focus:border-emerald-400 focus:ring-4 focus:ring-emerald-100" />
          <input value={teamBColour} onChange={(event) => setTeamBColour(event.target.value)} placeholder="Team B colours *" className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-slate-950 outline-none placeholder:text-slate-400 focus:border-emerald-400 focus:ring-4 focus:ring-emerald-100" />
        </div>

        <select value={coachedTeam} onChange={(event) => setCoachedTeam(event.target.value)} className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-4 text-slate-950 outline-none focus:border-emerald-400 focus:ring-4 focus:ring-emerald-100">
          <option value="">Which team are you coaching? *</option>
          {teamA ? <option value={teamA}>{teamA}</option> : null}
          {teamB ? <option value={teamB}>{teamB}</option> : null}
        </select>

        <div className="rounded-3xl border border-slate-200 bg-slate-50 p-4">
          <p className="text-sm font-bold text-slate-950">Final Score</p>
          <div className="mt-3 grid gap-3 md:grid-cols-2">
            <div className="rounded-2xl bg-white p-3 shadow-sm">
              <p className="mb-2 text-xs font-semibold text-slate-500">{teamA || 'Team A'}</p>
              <div className="grid grid-cols-2 gap-2">
                <input type="number" min="0" value={teamAGoals} onChange={(event) => setTeamAGoals(event.target.value)} placeholder="Goals" className="rounded-xl border border-slate-200 px-3 py-2 text-slate-950 outline-none" />
                <input type="number" min="0" value={teamAPoints} onChange={(event) => setTeamAPoints(event.target.value)} placeholder="Points" className="rounded-xl border border-slate-200 px-3 py-2 text-slate-950 outline-none" />
              </div>
            </div>
            <div className="rounded-2xl bg-white p-3 shadow-sm">
              <p className="mb-2 text-xs font-semibold text-slate-500">{teamB || 'Team B'}</p>
              <div className="grid grid-cols-2 gap-2">
                <input type="number" min="0" value={teamBGoals} onChange={(event) => setTeamBGoals(event.target.value)} placeholder="Goals" className="rounded-xl border border-slate-200 px-3 py-2 text-slate-950 outline-none" />
                <input type="number" min="0" value={teamBPoints} onChange={(event) => setTeamBPoints(event.target.value)} placeholder="Points" className="rounded-xl border border-slate-200 px-3 py-2 text-slate-950 outline-none" />
              </div>
            </div>
          </div>
        </div>

        <input value={competition} onChange={(event) => setCompetition(event.target.value)} placeholder="Competition / match type" className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-slate-950 outline-none placeholder:text-slate-400 focus:border-emerald-400 focus:ring-4 focus:ring-emerald-100" />

        <textarea value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Optional coach notes: key moments, timestamps, tactical focus, injuries, conditions, or areas you want reviewed." rows={4} className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-4 text-slate-950 outline-none placeholder:text-slate-400 focus:border-emerald-400 focus:ring-4 focus:ring-emerald-100" />

        <button onClick={analyse} disabled={!requiredFieldsComplete || status === 'processing'} className="w-full rounded-2xl bg-emerald-600 px-6 py-4 font-bold text-white shadow-lg shadow-emerald-600/20 transition hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-40">
          {status === 'processing' ? 'Generating analysis...' : 'Generate AI Match Report'}
        </button>

        <p className="text-center text-xs text-slate-500">Required: teams, colours, coached team and structured goals/points score.</p>
      </div>

      {status === 'error' ? <div className="mt-5 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm font-medium text-red-700">{error}</div> : null}

      {status === 'processing' ? <div className="mt-6 rounded-2xl bg-emerald-50 p-5 text-sm font-medium text-emerald-700">Analysing match context, transcript, sampled frames and coaching inputs...</div> : null}

      {status === 'complete' && report ? (
        <div className="mt-6 rounded-3xl border border-emerald-100 bg-emerald-50 p-6">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div>
              <p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-700">Report Ready</p>
              <h3 className="mt-2 text-2xl font-black text-slate-950">{matchTitle}</h3>
              <p className="mt-2 text-sm font-semibold text-slate-600">{report.scoreline}</p>
            </div>
            <button onClick={() => downloadReport(report, matchTitle)} className="rounded-2xl bg-slate-950 px-5 py-4 text-sm font-bold text-white shadow-lg shadow-slate-900/20 transition hover:bg-slate-800">
              Download Premium Report
            </button>
          </div>

          <div className="mt-5 rounded-2xl bg-white p-5 shadow-sm">
            <h4 className="font-bold text-slate-950">Quick Summary</h4>
            <p className="mt-3 line-clamp-4 text-sm leading-7 text-slate-600">{report.summary}</p>
          </div>

          <p className="mt-4 text-xs text-slate-500">The detailed tactical breakdown is kept inside the downloadable report to keep the workspace clean.</p>
        </div>
      ) : null}
    </div>
  )
}
