import { NextResponse } from 'next/server'

function safe(value: unknown, fallback = '') {
  const text = String(value ?? fallback)
  return text.trim() || fallback
}

function statLine(label: string, item: any) {
  if (!item) return `| ${label} | Unknown | Low confidence |`
  return `| ${label} | ${safe(item.value, 'Unknown')} | ${safe(item.confidence, 'Low confidence')} |`
}

function buildManagerMarkdown(job: any) {
  const result = job?.result || {}
  const facts = result.matchFacts || {}
  const evidence = result.matchEvidence || {}
  const stats = evidence.managerStatSummary || {}
  const analysis = safe(result.analysis)
  const sequences = Array.isArray(result.tacticalSequences) ? result.tacticalSequences : []
  const clips = Array.isArray(result.clips) ? result.clips : []
  const timeline = result.keyMomentsTimeline || {}

  const coached = safe(facts.coachedTeam, 'Coached Team')
  const opposition = facts.teamA === facts.coachedTeam ? facts.teamB : facts.teamA

  const lines = [
    `# ${coached} Manager Report`,
    '',
    '## 1. Match Snapshot',
    '',
    `| Item | Detail |`,
    `|---|---|`,
    `| Fixture | ${safe(facts.teamA, 'Team A')} vs ${safe(facts.teamB, 'Team B')} |`,
    `| Scoreline | ${safe(facts.scoreline, 'Unavailable')} |`,
    `| Result | ${coached} ${safe(facts.coachedTeamResult, 'finished')} by ${safe(facts.margin, 'Unknown')} point(s) |`,
    `| Opposition | ${safe(opposition, 'Opposition')} |`,
    '',
    '## 2. Manager Stats',
    '',
    '| Stat | Output | Confidence |',
    '|---|---|---|',
    statLine('Score', stats.score),
    statLine('Result', stats.result),
    statLine('Goals For', stats.goalsFor),
    statLine('Goals Against', stats.goalsAgainst),
    statLine('Points For', stats.pointsFor),
    statLine('Points Against', stats.pointsAgainst),
    statLine('Turnovers Won', stats.turnoversWon),
    statLine('Turnovers Lost', stats.turnoversLost),
    statLine('Positive Transitions', stats.positiveTransitions),
    statLine('Negative Transitions', stats.negativeTransitions),
    statLine('Breaking Ball Contests', stats.breakingBallContests),
    statLine('Kickouts Identified', stats.kickoutsIdentified),
    statLine('Kickouts Retained', stats.kickoutsRetained),
    statLine('Main Battle Zone', stats.mainBattleZone),
    '',
    '## 3. Tactical Story',
    '',
    ...(Array.isArray(stats.managerSummary) && stats.managerSummary.length ? stats.managerSummary.map((item: string) => `- ${item}`) : ['- Tactical story unavailable.']),
    '',
    '## 4. Tactical Sequences Worth Reviewing',
    '',
    '| Time | Sequence | Zone | Outcome | Coaching Note |',
    '|---|---|---|---|---|',
    ...(sequences.length ? sequences.slice(0, 12).map((s: any) => `| ${safe(s.time, 'Unknown')} | ${safe(s.phaseChain, 'Sequence')} | ${safe(s.dominantZone, 'Unknown')} | ${safe(s.finalOutcome, 'Unknown')} | ${safe(s.coachingSummary, 'Review spacing, support and decision-making.')} |`) : ['| Unknown | No reliable sequence surfaced | Unknown | Unknown | Review match video manually for tactical sequence detail. |']),
    '',
    '## 5. Review Clips',
    '',
    ...(clips.length ? clips.map((clip: any, index: number) => `- Clip ${index + 1}: ${safe(clip.time, 'Unknown')} — ${safe(clip.type, 'Review clip')} — ${safe(clip.downloadPath, '')}`) : ['- No downloadable clips were available for this report. Timeline timestamps may still be available in the web report.']),
    '',
    '## 6. AI Report Detail',
    '',
    analysis || 'No full report text was returned.',
    '',
    '---',
    'Generated by Gaelic Coach AI. Estimated metrics should be reviewed against video evidence before being treated as official statistics.'
  ]

  return lines.join('\n')
}

export async function GET(_request: Request, context: { params: { jobId: string } }) {
  try {
    const workerUrl = process.env.WORKER_API_URL?.replace(/\/$/, '')
    if (!workerUrl) return NextResponse.json({ error: 'WORKER_API_URL is not configured.' }, { status: 500 })

    const response = await fetch(`${workerUrl}/analysis-jobs/${context.params.jobId}`, { cache: 'no-store' })
    const job = await response.json()

    if (!response.ok) return NextResponse.json(job, { status: response.status })
    if (job.status !== 'complete' || !job.result) {
      return NextResponse.json({ error: 'Report is not ready yet.' }, { status: 409 })
    }

    const markdown = buildManagerMarkdown(job)
    return new NextResponse(markdown, {
      status: 200,
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        'Content-Disposition': `attachment; filename="gaelic-coach-ai-${context.params.jobId}.md"`,
        'Cache-Control': 'no-store'
      }
    })
  } catch {
    return NextResponse.json({ error: 'Unable to download report.' }, { status: 500 })
  }
}
